#!/bin/bash

#
# Example:
# 
#   "github.com/stretchr/testify"
#
# should become:
#
#   testify "github.com/stretchr/testify-9a3bde9" //depset
#


_usage() { 
cat<<EOF

    DepSet

    Usage:
      depset [commands]

    Commands:

      freeze - Save all dependencies to current version and 
               alias all imports



EOF

}


main() {

_usage

}
