#!/bin/bash

#
# Example:
# 
#   "github.com/stretchr/testify"
#
# should become:
#
#   testify "github.com/stretchr/testify-9a3bde9" //depset
#


_usage() { 
cat<<EOF

    DepSet

    Usage:
      depset [commands]

    Commands:

      freeze - Save all dependencies to current version and 
               alias all imports



EOF

}


_init() {

  if [ -z "$GOROOT" ]; then
    echo "GOROOT not set"
    exit 1
  fi

  if [ -z "$GOPATH" ]; then
    echo "GOPATH not set"
    exit 1
  fi

}




_listdeps() {

  deps=($(grep "github.com\|gopkg.in\|code.google.com\|bitbucket.org\|azul3d.org" ${1} | sed -e 's/\"//' -e 's/\"//'))

  for dep in "${deps[@]}"
  do
    _freeze_dep ${dep}
  done

}


_show_git_root() {

  cd $1
  base=`git rev-parse --show-toplevel`
  echo $base
  
}



_freeze_dep() {

  echo "Searching for ${GOPATH}/src/${1}"
  if [ -d "${GOPATH}/src/${1}" ]; then
    root=$(_show_git_root "${GOPATH}/src/${1}")
    echo "Git root is $root"
  else
    echo "not found" 
  fi

}



main() {

_init
_usage
_listdeps $1

}

main ${1}

